print("Program for entering the input to the System")
name=input("Enter your name ")
rollno=input("Enter your rollno ")
age=input("Enter your age ")
section=input("Enter your section ")
print("Name is "+name)
print("Rollno is "+rollno)
print("Your age is "+age)
print("Your Section is "+section)
