print("Karthik is a good {Adjective}")
print("Karthik studies is {noun}")
print("Karthik always in a state of {adjective}")
print("karthik Rollno is {Adjective}")
name=input("karthik is a: ")
clg=input("Enter the name of clg: ")
rollno=input("Rollno of karthik is: ")
state=input("karthik is always in a state of: ")
print("Karthik is a good "+name)
print("Karthik studies is "+clg)
print("Karthik always in a state of "+rollno)
print("karthik Rollno is "+state)