def sum(a,b):
    return int(a)+int(b)
def sub(a,b):
    return int(a)-int(b)
def mul(a,b):
    return int(a)*int(b)
def div(a,b):
    return int(a)/int(b)
def mod(a,b):
    return int(a)%int(b)